data-mermaid/mermaid-api

src/api/admin/base.py
src/api/admin/mermaid.py

Look up values from model choices if present

---

src/api/submission/utils.py
src/api/submission/validations.py

Fix Exception message handling

[M1163] Handle bad transect field data types

---

README.md
fabfile.py

This will align the documentation with the changes done in the b07b9bbee30d734832734ca7deea0ac5929b27f2 commit.

Update fab tasks

---

src/api/auth_backends.py
src/api/ingest/benthicpit_serializer.py
src/api/ingest/serializers.py
src/api/ingest/utils.py
src/api/models/base.py
src/api/signals.py
src/api/submission/mixins.py
src/tools/management/commands/datachanges.py
src/tools/management/commands/dbbackup.py
src/tools/management/commands/dbrestore.py

Some import optimizations and a couple other changes.

Small refactoring

---

Dockerfile
ci_cd/simpleq.supervisor
src/app/settings.py
src/simpleq/README.md
src/simpleq/jobs.py
src/simpleq/management/commands/simpleq_worker.py
src/simpleq/queues.py
src/simpleq/scripts/simpleq_test.py
src/simpleq/workers.py

Ticket will be split into 2 pull requests first being the queueing system, second (yet to come) will be the summary endpoint caching .

[M1429] Job, Queue, Worker

---

src/api/models/sql_models/base.py
src/sqltables/README.md
src/sqltables/__init__.py
src/sqltables/datastructures.py
src/sqltables/query.py
src/sqltables/tests/test_sql_table.py

- removed all the unsupported join code

[M1531] Refactor SQL Tables to use Dictionary instead of tuple for sql params

---

src/api/resources/fish_species.py
src/api/resources/sync/pull.py
src/api/resources/sync/views.py

- have also removed fish species cache

[M1561] Improve performance of revision pull for fish species

---

src/api/resources/benthic_attribute.py
src/api/resources/fish_family.py
src/api/resources/fish_genus.py
src/api/resources/fish_species.py
src/api/tests/fixtures/benthic_attributes.py
src/api/tests/fixtures/choices.py
src/api/tests/fixtures/fish_attributes.py
src/api/tests/test_benthic_attributes.py
src/api/tests/test_fish_attributes.py

- All attribute endpoints can now be filtered by regions (1 to many)

[M1532] Filter attributes by regions

---

src/api/resources/collect_record.py
src/api/tests/fixtures/projects.py
src/api/tests/fixtures/revisions_setup.py
src/api/tests/test_collect_record.py

- includes removing show all collect records (don't show collect records to non-owners) 
- added tests for the changes

M1539: Extend CollectRecordOwner permission to edit delete methods

---

src/api/resources/base.py
src/api/tests/fixtures/projects.py
src/api/tests/test_filters.py

SafeSearchFilter extends SearchFilter by including validation of regex search terms

[M1570] Change base api viewset to use SafeSearchFilter

---

src/api/submission/protocol_validations.py
src/api/submission/writer.py
src/api/tests/fixtures/collect_records.py
src/api/tests/test_protocol_validations.py

- **BIG CHANGE ALERT:** if the serializer validation fails, no further validations are run and a response is returned

[M1584] Move serializer validation so it's run first during validation

---

src/api/resources/collect_record.py
src/api/submission/utils.py
src/api/submission/validations2/base.py
src/api/submission/validations2/belt_fish.py
src/api/tests/fixtures/collect_records.py
src/api/tests/test_sample_unit_method.py
src/api/utils/sample_unit_methods.py

When submitting a collect record validation gets run again but submission wasn't supporting version 2 validation.
This PR also includes a fix on how overall validation statuses are tracked

[M458] Add version 2 validation check to collect record submission

---

Makefile
src/api/submission/validations2/belt_fish.py
src/api/submission/validations2/validators/fish_family.py
src/api/tests/fixtures/projects.py
src/api/tests/test_revision_views.py
src/api/tests/validators/test_fish_family.py

When creating a fish attribute lookup wasn't handling case of fish attribute not being set

[M1611] Bug fix in fish family subset

---

src/api/fields.py
src/api/ingest/__init__.py
src/api/ingest/benthicpqt_serializer.py
src/api/ingest/bleaching_serializer.py
src/api/ingest/utils.py
src/api/models/mermaid.py
src/api/resources/collect_record.py
src/api/submission/utils.py
src/api/tests/ingest_data/benthicpqt.csv
src/api/tests/test_ingest.py
src/tools/management/commands/ingest.py

- Includes serializers and tests

[M1606] Benthic Photo Quadrat ingest

---

Makefile
docker-compose.yml
src/api/signals/__init__.py
src/api/signals/summaries.py
src/api/utils/q.py
src/api/utils/summaries.py
src/app/settings.py
src/simpleq/README.md
src/simpleq/jobs.py
src/simpleq/queues.py
src/simpleq/scripts/simpleq_test.py

- Added another container for elasticmq (SQS clone) for local testing
- Send summary updates that were being called in signals to simpleq jobs

[M1643] Run summary updates in simpleq worker

---

src/api/resources/mixins.py
src/api/resources/sample_units/beltfishmethod.py
src/api/resources/sample_units/benthiclitmethod.py
src/api/resources/sample_units/benthicphotoquadrattransectmethod.py
src/api/resources/sample_units/benthicpitmethod.py
src/api/resources/sample_units/bleachingquadratcollectionmethod.py
src/api/resources/sample_units/habitatcomplexitymethod.py
src/api/utils/sample_unit_methods.py

Fishbelt has already been done but need to do the other protocols
- benthic pit
- benthic lit
- habitat complexity
- bleaching
- benthic photo quadrat
Card: [1668](https://trello.com/c/wweVFHhz/1668-add-edit-to-sample-unit-methods)

[M1668] Add /edit to sample unit methods

---

src/api/resources/profile.py
src/api/resources/project.py
src/api/tests/fixtures/projects.py
src/api/tests/test_project.py

Card: [#1568](https://trello.com/c/NO27bLlH/1568-make-profile-email-case-insensitive)

[M1568] Make profile email case-insensitive when adding to project

---

src/api/utils/replace.py

Card [#711](https://trello.com/c/CviXxiz9/711-update-current-user-crs-after-transferring-them-away)

[M711] Fix revision updates when transferring collect records to another user

---

src/api/submission/validations2/validators/site.py
src/api/tests/validators/test_site.py

Card: #[1648](https://trello.com/c/XGXSyYE0/1648-make-unique-site-validation-use-submitted-sus-only)

[M1648] Make unique site validation use submitted SUs only

---

src/api/resources/me.py
src/api/resources/project.py
src/api/utils/project.py

Card [#717](https://trello.com/c/AoqlI9xP/717-add-collecting-and-submitted-record-counts-to-project-endpoint)

[M717] Add num_active_sample_units and num_sample_units to projects endpoint

---

iac/stacks/common.py

I manually created a cert while working on webapp and using this [more general] cert will simplify things. This is not a blocker.

use combined ssl cert

---

.env.sample
iac/stacks/api.py
iac/stacks/constructs/worker.py
src/app/settings.py

parameterize the queue name and changed the name itself

---

.github/workflows/_test.yml
.github/workflows/deploy-cdk.yml
.github/workflows/pr.yml

I'm also testing the branch protection in this PR. I've updated the rules to ensure that tests pass before merging.

Inject CICD test job placeholder

---

iac/settings/dev.py
iac/settings/prod.py
iac/settings/settings.py
iac/stacks/api.py

create separate auth0 creds for each env

[M1844] make auth0 secrets dynamic

---

requirements.txt
src/api/ingest/attributes_ingester.py
src/api/reports/summary_report.py
src/api/tests/test_project_edit_tracking.py
src/api/utils/castutils.py

Add data values were strings so when they are written to excel worksheet the format was being set as General.  This PR casts number strings to float or int.

[M1852] Excel reports recognize number values

---

requirements.txt

ran tests and did a couple spot checks but otherwise not sure how to QA

[M168] upgrade boto3 and therefore botocore to remove deprecation message

---

iac/app.py
iac/install_cdk.sh
iac/stacks/api.py
iac/stacks/common.py
iac/stacks/constructs/worker.py
src/app/settings.py

This PR adds the bucket, SQS queue and ECS worker. 
Also changes the queue type to standard from fifo. 
Merge PR #437 first.

M664 Add Image Processing resources

---

iac/stacks/constructs/worker.py

Add more permissions so Workers can delete and send messages. See the ticket for reference.

M984 Add more SQS Permission

---

Dockerfile
iac/settings/__init__.py
iac/settings/dev.py
iac/settings/prod.py
iac/settings/settings.py
iac/settings/utils.py
iac/stacks/api.py
iac/stacks/constructs/queue.py
iac/stacks/constructs/worker.py
iac/stacks/static_site.py

This PR has changes to make the names of resources more general. Current naming is misleading and needs to be updated. This PR will replace a number of ECS, SNS, and SQS resources.

Rename AWS Resources
